name: publish
on:
  push:
    tags:
    - 'v.*'

jobs:
  # Publishes mtrack to crates.io.
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update apt
      run: sudo apt update
    - name: Install alsa
      run: sudo apt-get install -y libasound2-dev
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Run publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish
